[local]
localhost ansible_connection=local

[proxmox]
# Add your proxmox hosts here, example:
pve-5 ansible_host=192.168.20.40

[k8s_nodes]
k8s-master ansible_host=192.168.20.51 ansible_user=debian
k8s-node1 ansible_host=192.168.20.52 ansible_user=debian
